// const firstEl=document.getElementById("iden");
//const firstEl=document.getElementsByClassName("class")[0];
const firstEl = document.querySelector("div");
// firstEl.innerText= "I am here!";
firstEl.innerHTML="I`m <strong>here</strong>!";
firstEl.classList.add("added");
const body = document.querySelector("body");
body.innerHTML+="<div class='added'>I`m here x2</div>";
const newEl=document.createElement("div");
newEl.innerText="I`m here x3";
newEl.classList.add("added");
body.appendChild(newEl);